"""Snapshot-style tests for all three config generators."""

from __future__ import annotations

from pathlib import Path

import pytest

from proxysmith.core.parser import load_config
from proxysmith.core.resolver import resolve
from proxysmith.generators import CaddyGenerator, NginxGenerator, TraefikGenerator

FIXTURES = Path(__file__).parent / "fixtures"


def _load(name: str):
    """Load and resolve a fixture config."""
    cfg = load_config(FIXTURES / name)
    return resolve(cfg)


# --------------------------------------------------------------------------- #
# Nginx                                                                        #
# --------------------------------------------------------------------------- #


class TestNginxGenerator:
    def test_generates_one_file(self):
        files = NginxGenerator().generate(_load("full.toml"))
        assert len(files) == 1
        assert files[0].filename == "nginx/proxysmith.conf"

    def test_contains_all_upstreams(self):
        content = NginxGenerator().generate(_load("full.toml"))[0].content
        assert "upstream proxysmith_plex" in content
        assert "upstream proxysmith_immich" in content
        assert "upstream proxysmith_ollama" in content
        assert "upstream proxysmith_homepage" in content

    def test_server_names(self):
        content = NginxGenerator().generate(_load("full.toml"))[0].content
        assert "server_name plex.home.example.com" in content
        assert "server_name photos.home.example.com" in content
        assert "server_name llm.home.example.com" in content
        assert "server_name dash.home.example.com" in content

    def test_ssl_redirect_present(self):
        content = NginxGenerator().generate(_load("full.toml"))[0].content
        assert "return 301  https://$host$request_uri" in content

    def test_ssl_certificates_referenced(self):
        content = NginxGenerator().generate(_load("full.toml"))[0].content
        assert "ssl_certificate" in content
        assert "letsencrypt" in content

    def test_websocket_upgrade(self):
        content = NginxGenerator().generate(_load("full.toml"))[0].content
        # plex has websocket=true
        assert 'proxy_set_header   Upgrade            $http_upgrade' in content

    def test_custom_headers_injected(self):
        content = NginxGenerator().generate(_load("full.toml"))[0].content
        assert 'X-Plex-Client-Identifier' in content

    def test_basic_auth_directive(self):
        content = NginxGenerator().generate(_load("full.toml"))[0].content
        assert "auth_basic" in content
        assert "htpasswd/ollama" in content

    def test_rate_limit_zone(self):
        content = NginxGenerator().generate(_load("full.toml"))[0].content
        assert "ollama_limit" in content

    def test_max_upload_size(self):
        content = NginxGenerator().generate(_load("full.toml"))[0].content
        assert "client_max_body_size 10G" in content

    def test_no_ssl_when_mode_none(self):
        content = NginxGenerator().generate(_load("minimal.toml"))[0].content
        assert "ssl_certificate" not in content
        assert "return 301" not in content

    def test_generated_by_comment(self):
        content = NginxGenerator().generate(_load("minimal.toml"))[0].content
        assert "Generated by ProxySmith" in content

    def test_security_headers_present(self):
        content = NginxGenerator().generate(_load("full.toml"))[0].content
        assert "X-Frame-Options" in content
        assert "X-Content-Type-Options" in content
        assert "Strict-Transport-Security" in content

    def test_proxy_headers_chain(self):
        content = NginxGenerator().generate(_load("minimal.toml"))[0].content
        assert "X-Real-IP" in content
        assert "X-Forwarded-For" in content
        assert "X-Forwarded-Proto" in content


# --------------------------------------------------------------------------- #
# Caddy                                                                        #
# --------------------------------------------------------------------------- #


class TestCaddyGenerator:
    def test_generates_one_file(self):
        files = CaddyGenerator().generate(_load("full.toml"))
        assert len(files) == 1
        assert files[0].filename == "caddy/Caddyfile"

    def test_global_email_block(self):
        content = CaddyGenerator().generate(_load("full.toml"))[0].content
        assert "email admin@example.com" in content

    def test_all_fqdns_present(self):
        content = CaddyGenerator().generate(_load("full.toml"))[0].content
        assert "plex.home.example.com" in content
        assert "photos.home.example.com" in content
        assert "llm.home.example.com" in content
        assert "dash.home.example.com" in content

    def test_reverse_proxy_directives(self):
        content = CaddyGenerator().generate(_load("full.toml"))[0].content
        assert "reverse_proxy 192.168.1.50:32400" in content
        assert "reverse_proxy 192.168.1.50:2283" in content

    def test_tls_off_when_none(self):
        content = CaddyGenerator().generate(_load("minimal.toml"))[0].content
        assert "tls off" in content

    def test_basic_auth_directive(self):
        content = CaddyGenerator().generate(_load("full.toml"))[0].content
        assert "basicauth" in content

    def test_request_body_limit(self):
        content = CaddyGenerator().generate(_load("full.toml"))[0].content
        assert "max_size 10G" in content

    def test_generated_by_comment(self):
        content = CaddyGenerator().generate(_load("minimal.toml"))[0].content
        assert "Generated by ProxySmith" in content

    def test_security_headers(self):
        content = CaddyGenerator().generate(_load("full.toml"))[0].content
        assert "X-Frame-Options" in content
        assert "X-Content-Type-Options" in content


# --------------------------------------------------------------------------- #
# Traefik                                                                      #
# --------------------------------------------------------------------------- #


class TestTraefikGenerator:
    def test_generates_two_files(self):
        files = TraefikGenerator().generate(_load("full.toml"))
        assert len(files) == 2
        filenames = {f.filename for f in files}
        assert "traefik/docker-compose.labels.yml" in filenames
        assert "traefik/file-provider.yml" in filenames

    def _docker(self, fixture="full.toml"):
        return next(
            f for f in TraefikGenerator().generate(_load(fixture))
            if "docker" in f.filename
        ).content

    def _file(self, fixture="full.toml"):
        return next(
            f for f in TraefikGenerator().generate(_load(fixture))
            if "file" in f.filename
        ).content

    def test_docker_labels_contain_fqdns(self):
        content = self._docker()
        assert "plex.home.example.com" in content
        assert "photos.home.example.com" in content

    def test_docker_labels_https_redirect(self):
        content = self._docker()
        assert "https-redirect" in content

    def test_docker_cert_resolver(self):
        content = self._docker()
        assert "letsencrypt" in content

    def test_file_provider_routers(self):
        content = self._file()
        assert "routers:" in content
        assert "services:" in content
        assert "middlewares:" in content

    def test_file_provider_fqdns(self):
        content = self._file()
        assert "plex.home.example.com" in content
        assert "photos.home.example.com" in content

    def test_file_provider_health_check(self):
        content = self._file()
        assert "healthCheck:" in content

    def test_rate_limit_in_docker(self):
        content = self._docker()
        assert "ratelimit" in content

    def test_basic_auth_in_docker(self):
        content = self._docker()
        assert "basicauth" in content

    def test_no_ssl_when_none(self):
        content = self._file("minimal.toml")
        assert "letsencrypt" not in content
        assert "websecure" not in content

    def test_generated_by_comment(self):
        assert "Generated by ProxySmith" in self._docker()
        assert "Generated by ProxySmith" in self._file()

    def test_security_headers_middleware(self):
        content = self._file()
        assert "securityheaders" in content
        assert "frameDeny" in content


# --------------------------------------------------------------------------- #
# Resolver                                                                     #
# --------------------------------------------------------------------------- #


class TestResolver:
    def test_fqdn_construction(self):
        cfg = load_config(FIXTURES / "full.toml")
        resolved = resolve(cfg)
        fqdns = {svc.fqdn for svc in resolved.services}
        assert "plex.home.example.com" in fqdns
        assert "photos.home.example.com" in fqdns

    def test_upstream_name(self):
        cfg = load_config(FIXTURES / "full.toml")
        resolved = resolve(cfg)
        names = {svc.upstream_name for svc in resolved.services}
        assert "proxysmith_plex" in names

    def test_use_ssl_true_for_auto(self):
        cfg = load_config(FIXTURES / "full.toml")
        resolved = resolve(cfg)
        assert all(svc.use_ssl for svc in resolved.services)

    def test_use_ssl_false_for_none(self):
        cfg = load_config(FIXTURES / "minimal.toml")
        resolved = resolve(cfg)
        assert all(not svc.use_ssl for svc in resolved.services)
